version: '3.7'
services:
  db:
    tty: true
    image: mysql:5
    ports:
      - "33061:3306"
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  app:
    tty: true
    ports:
      - "3306:33061"
    build: .
    depends_on:
      - db
