version: '3.7'
services:
  db:
    tty: true
    image: mysql:5
    ports:
      - "11235:11235"
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_TCP_PORT: 11235
  app:
    tty: true
    ports:
      - "11235:11235"
    build: .
    depends_on:
      - db
