name: Lint

on:
  push:
    branches: ["main"]
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1

      - name: format
        run: ruff format --diff

      - name: lint
        run: ruff check --diff
